# Generated by Django 2.1 on 2020-10-23 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomDomain', models.CharField(max_length=100)),
                ('nomOrg', models.CharField(max_length=100)),
                ('deprt', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
